{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "a48b0c46-6e25-4fa4-9788-73a80c667822",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "\"\\nThe reason is that it's difficult to contain all exception cases in my custom class.\\nThat's why we need to use the superclass Exception to inherit all exceptions that may arise.\\n\\n\""
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Q1\n",
    "'''\n",
    "The reason is that it's difficult to contain all exception cases in my custom class.\n",
    "That's why we need to use the superclass Exception to inherit all exceptions that may arise.\n",
    "\n",
    "'''"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "c98c237c-8c43-4ccc-931d-e7c0dbb2fdaa",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Q2\n",
    "def get_all_subclasses(cls):\n",
    "    all_subclasses = []\n",
    "    \n",
    "    for subclass in cls.__subclasses__():\n",
    "        all_subclasses.append(subclass)\n",
    "        all_subclasses.extend(get_all_subclasses(subclass))\n",
    "    return all_subclasses"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "416ccfac-9711-49db-98ba-9fecf2ba0e0f",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[TypeError,\n",
       " decimal.FloatOperation,\n",
       " email.errors.MultipartConversionError,\n",
       " StopAsyncIteration,\n",
       " StopIteration,\n",
       " ImportError,\n",
       " ModuleNotFoundError,\n",
       " zipimport.ZipImportError,\n",
       " OSError,\n",
       " ConnectionError,\n",
       " BrokenPipeError,\n",
       " ConnectionAbortedError,\n",
       " ConnectionRefusedError,\n",
       " ConnectionResetError,\n",
       " http.client.RemoteDisconnected,\n",
       " BlockingIOError,\n",
       " ChildProcessError,\n",
       " FileExistsError,\n",
       " FileNotFoundError,\n",
       " IsADirectoryError,\n",
       " NotADirectoryError,\n",
       " InterruptedError,\n",
       " zmq.error.InterruptedSystemCall,\n",
       " PermissionError,\n",
       " ProcessLookupError,\n",
       " TimeoutError,\n",
       " io.UnsupportedOperation,\n",
       " signal.itimer_error,\n",
       " socket.herror,\n",
       " socket.gaierror,\n",
       " ssl.SSLError,\n",
       " ssl.SSLCertVerificationError,\n",
       " ssl.SSLZeroReturnError,\n",
       " ssl.SSLWantWriteError,\n",
       " ssl.SSLWantReadError,\n",
       " ssl.SSLSyscallError,\n",
       " ssl.SSLEOFError,\n",
       " shutil.Error,\n",
       " shutil.SameFileError,\n",
       " shutil.SpecialFileError,\n",
       " shutil.ExecError,\n",
       " shutil.ReadError,\n",
       " urllib.error.URLError,\n",
       " urllib.error.HTTPError,\n",
       " urllib.error.ContentTooShortError,\n",
       " gzip.BadGzipFile,\n",
       " EOFError,\n",
       " asyncio.exceptions.IncompleteReadError,\n",
       " RuntimeError,\n",
       " RecursionError,\n",
       " NotImplementedError,\n",
       " zmq.error.ZMQVersionError,\n",
       " IPython.core.error.StdinNotImplementedError,\n",
       " _frozen_importlib._DeadlockError,\n",
       " threading.BrokenBarrierError,\n",
       " concurrent.futures._base.BrokenExecutor,\n",
       " concurrent.futures.thread.BrokenThreadPool,\n",
       " asyncio.exceptions.SendfileNotAvailableError,\n",
       " pkg_resources.ExtractionError,\n",
       " _pydevd_bundle.pydevd_vars.VariableError,\n",
       " NameError,\n",
       " UnboundLocalError,\n",
       " AttributeError,\n",
       " dataclasses.FrozenInstanceError,\n",
       " SyntaxError,\n",
       " IndentationError,\n",
       " TabError,\n",
       " LookupError,\n",
       " IndexError,\n",
       " KeyError,\n",
       " jupyter_client.kernelspec.NoSuchKernel,\n",
       " IPython.terminal.pt_inputhooks.UnknownBackend,\n",
       " encodings.CodecRegistryError,\n",
       " ValueError,\n",
       " UnicodeError,\n",
       " UnicodeEncodeError,\n",
       " UnicodeDecodeError,\n",
       " UnicodeTranslateError,\n",
       " io.UnsupportedOperation,\n",
       " json.decoder.JSONDecodeError,\n",
       " ssl.SSLCertVerificationError,\n",
       " binascii.Error,\n",
       " _hashlib.UnsupportedDigestmodError,\n",
       " calendar.IllegalMonthError,\n",
       " calendar.IllegalWeekdayError,\n",
       " dateutil.parser._parser.ParserError,\n",
       " pygments.util.ClassNotFound,\n",
       " IPython.lib.clipboard.ClipboardEmpty,\n",
       " email.errors.MessageDefect,\n",
       " email.errors.NoBoundaryInMultipartDefect,\n",
       " email.errors.StartBoundaryNotFoundDefect,\n",
       " email.errors.CloseBoundaryNotFoundDefect,\n",
       " email.errors.FirstHeaderLineIsContinuationDefect,\n",
       " email.errors.MisplacedEnvelopeHeaderDefect,\n",
       " email.errors.MissingHeaderBodySeparatorDefect,\n",
       " email.errors.MultipartInvariantViolationDefect,\n",
       " email.errors.InvalidMultipartContentTransferEncodingDefect,\n",
       " email.errors.UndecodableBytesDefect,\n",
       " email.errors.InvalidBase64PaddingDefect,\n",
       " email.errors.InvalidBase64CharactersDefect,\n",
       " email.errors.InvalidBase64LengthDefect,\n",
       " email.errors.HeaderDefect,\n",
       " email.errors.InvalidHeaderDefect,\n",
       " email.errors.HeaderMissingRequiredValue,\n",
       " email.errors.NonPrintableDefect,\n",
       " email.errors.ObsoleteHeaderDefect,\n",
       " email.errors.NonASCIILocalPartDefect,\n",
       " email.errors.InvalidDateDefect,\n",
       " IPython.core.magics.code.MacroToEdit,\n",
       " plistlib.InvalidFileException,\n",
       " pkg_resources._vendor.more_itertools.more.UnequalIterablesError,\n",
       " pkg_resources.extern.packaging.version.InvalidVersion,\n",
       " pkg_resources._vendor.packaging._manylinux._ELFFileHeader._InvalidELFFileHeader,\n",
       " pkg_resources.extern.packaging.utils.InvalidWheelFilename,\n",
       " pkg_resources.extern.packaging.utils.InvalidSdistFilename,\n",
       " pkg_resources.extern.packaging.specifiers.InvalidSpecifier,\n",
       " pkg_resources.extern.packaging.markers.InvalidMarker,\n",
       " pkg_resources.extern.packaging.markers.UndefinedComparison,\n",
       " pkg_resources.extern.packaging.markers.UndefinedEnvironmentName,\n",
       " pkg_resources.extern.packaging.requirements.InvalidRequirement,\n",
       " pkg_resources.RequirementParseError,\n",
       " packaging.version.InvalidVersion,\n",
       " AssertionError,\n",
       " ArithmeticError,\n",
       " FloatingPointError,\n",
       " OverflowError,\n",
       " ZeroDivisionError,\n",
       " decimal.DivisionByZero,\n",
       " decimal.DivisionUndefined,\n",
       " decimal.DecimalException,\n",
       " decimal.Clamped,\n",
       " decimal.Rounded,\n",
       " decimal.Underflow,\n",
       " decimal.Overflow,\n",
       " decimal.Inexact,\n",
       " decimal.Underflow,\n",
       " decimal.Overflow,\n",
       " decimal.Subnormal,\n",
       " decimal.Underflow,\n",
       " decimal.DivisionByZero,\n",
       " decimal.FloatOperation,\n",
       " decimal.InvalidOperation,\n",
       " decimal.ConversionSyntax,\n",
       " decimal.DivisionImpossible,\n",
       " decimal.DivisionUndefined,\n",
       " decimal.InvalidContext,\n",
       " SystemError,\n",
       " encodings.CodecRegistryError,\n",
       " ReferenceError,\n",
       " MemoryError,\n",
       " BufferError,\n",
       " Warning,\n",
       " UserWarning,\n",
       " getpass.GetPassWarning,\n",
       " IPython.core.formatters.FormatterWarning,\n",
       " EncodingWarning,\n",
       " DeprecationWarning,\n",
       " IPython.core.interactiveshell.ProvisionalWarning,\n",
       " PendingDeprecationWarning,\n",
       " SyntaxWarning,\n",
       " RuntimeWarning,\n",
       " zmq.asyncio.ProactorSelectorThreadWarning,\n",
       " dateutil.parser._parser.UnknownTimezoneWarning,\n",
       " pkg_resources.PEP440Warning,\n",
       " FutureWarning,\n",
       " IPython.core.completer.ProvisionalCompleterWarning,\n",
       " ImportWarning,\n",
       " UnicodeWarning,\n",
       " BytesWarning,\n",
       " ResourceWarning,\n",
       " dateutil.tz.DeprecatedTzFormatWarning,\n",
       " pkg_resources.PkgResourcesDeprecationWarning,\n",
       " warnings._OptionError,\n",
       " runpy._Error,\n",
       " re.error,\n",
       " sre_parse.Verbose,\n",
       " locale.Error,\n",
       " subprocess.SubprocessError,\n",
       " subprocess.CalledProcessError,\n",
       " subprocess.TimeoutExpired,\n",
       " tokenize.TokenError,\n",
       " tokenize.StopTokenizing,\n",
       " inspect.ClassFoundException,\n",
       " inspect.EndOfBlock,\n",
       " traitlets.traitlets.TraitError,\n",
       " copy.Error,\n",
       " concurrent.futures._base.Error,\n",
       " concurrent.futures._base.CancelledError,\n",
       " concurrent.futures._base.TimeoutError,\n",
       " concurrent.futures._base.InvalidStateError,\n",
       " socket._GiveupOnSendfile,\n",
       " struct.error,\n",
       " binascii.Incomplete,\n",
       " asyncio.exceptions.TimeoutError,\n",
       " asyncio.exceptions.InvalidStateError,\n",
       " asyncio.exceptions.LimitOverrunError,\n",
       " asyncio.queues.QueueEmpty,\n",
       " asyncio.queues.QueueFull,\n",
       " _queue.Empty,\n",
       " queue.Full,\n",
       " ctypes.ArgumentError,\n",
       " zmq.error.ZMQBaseError,\n",
       " zmq.error.ZMQError,\n",
       " zmq.error.ContextTerminated,\n",
       " zmq.error.Again,\n",
       " zmq.error.InterruptedSystemCall,\n",
       " zmq.error.ZMQBindError,\n",
       " zmq.error.NotDone,\n",
       " _pickle.PickleError,\n",
       " _pickle.PicklingError,\n",
       " _pickle.UnpicklingError,\n",
       " pickle._Stop,\n",
       " argparse.ArgumentError,\n",
       " argparse.ArgumentTypeError,\n",
       " traitlets.config.loader.ConfigError,\n",
       " traitlets.config.loader.ConfigLoaderError,\n",
       " traitlets.config.loader.ArgumentError,\n",
       " traitlets.config.loader.ConfigFileNotFound,\n",
       " traitlets.config.configurable.ConfigurableError,\n",
       " traitlets.config.configurable.MultipleInstanceError,\n",
       " traitlets.config.application.ApplicationError,\n",
       " zlib.error,\n",
       " tornado.util.TimeoutError,\n",
       " _curses.error,\n",
       " tornado.concurrent.ReturnValueIgnoredError,\n",
       " tornado.gen.KeyReuseError,\n",
       " tornado.gen.UnknownKeyError,\n",
       " tornado.gen.LeakedCallbackError,\n",
       " tornado.gen.BadYieldError,\n",
       " tornado.gen.ReturnValueIgnoredError,\n",
       " tornado.gen.Return,\n",
       " jupyter_client.channels.InvalidPortNumber,\n",
       " termios.error,\n",
       " _lzma.LZMAError,\n",
       " shutil.RegistryError,\n",
       " shutil._GiveupOnFastCopy,\n",
       " configparser.Error,\n",
       " configparser.NoSectionError,\n",
       " configparser.DuplicateSectionError,\n",
       " configparser.DuplicateOptionError,\n",
       " configparser.NoOptionError,\n",
       " configparser.InterpolationError,\n",
       " configparser.InterpolationMissingOptionError,\n",
       " configparser.InterpolationSyntaxError,\n",
       " configparser.InterpolationDepthError,\n",
       " configparser.ParsingError,\n",
       " configparser.MissingSectionHeaderError,\n",
       " jupyter_client.localinterfaces.NoIPAddresses,\n",
       " zipfile.BadZipFile,\n",
       " zipfile.LargeZipFile,\n",
       " entrypoints.BadEntryPoint,\n",
       " entrypoints.NoSuchEntryPoint,\n",
       " jupyter_client.multikernelmanager.DuplicateKernelError,\n",
       " pydoc.ErrorDuringImport,\n",
       " executing.executing.NotOneValueFound,\n",
       " pure_eval.utils.CannotEval,\n",
       " pygments.util.OptionError,\n",
       " bdb.BdbQuit,\n",
       " pdb.Restart,\n",
       " pexpect.exceptions.ExceptionPexpect,\n",
       " pexpect.exceptions.EOF,\n",
       " pexpect.exceptions.TIMEOUT,\n",
       " ptyprocess.util.PtyProcessError,\n",
       " IPython.utils.process.FindCmdError,\n",
       " IPython.utils.path.HomeDirError,\n",
       " IPython.core.profiledir.ProfileDirError,\n",
       " IPython.core.error.IPythonCoreError,\n",
       " IPython.core.error.TryNext,\n",
       " IPython.core.error.UsageError,\n",
       " IPython.core.error.StdinNotImplementedError,\n",
       " IPython.core.error.InputRejected,\n",
       " getopt.GetoptError,\n",
       " pygments.filters.ErrorToken,\n",
       " IPython.core.prefilter.PrefilterError,\n",
       " IPython.core.alias.AliasError,\n",
       " IPython.core.alias.InvalidAliasError,\n",
       " sqlite3.Error,\n",
       " sqlite3.InterfaceError,\n",
       " sqlite3.DatabaseError,\n",
       " sqlite3.InternalError,\n",
       " sqlite3.OperationalError,\n",
       " sqlite3.ProgrammingError,\n",
       " sqlite3.IntegrityError,\n",
       " sqlite3.DataError,\n",
       " sqlite3.NotSupportedError,\n",
       " sqlite3.Warning,\n",
       " IPython.core.interactiveshell.SpaceInInput,\n",
       " xml.dom.DOMException,\n",
       " xml.dom.IndexSizeErr,\n",
       " xml.dom.DomstringSizeErr,\n",
       " xml.dom.HierarchyRequestErr,\n",
       " xml.dom.WrongDocumentErr,\n",
       " xml.dom.InvalidCharacterErr,\n",
       " xml.dom.NoDataAllowedErr,\n",
       " xml.dom.NoModificationAllowedErr,\n",
       " xml.dom.NotFoundErr,\n",
       " xml.dom.NotSupportedErr,\n",
       " xml.dom.InuseAttributeErr,\n",
       " xml.dom.InvalidStateErr,\n",
       " xml.dom.SyntaxErr,\n",
       " xml.dom.InvalidModificationErr,\n",
       " xml.dom.NamespaceErr,\n",
       " xml.dom.InvalidAccessErr,\n",
       " xml.dom.ValidationErr,\n",
       " prompt_toolkit.validation.ValidationError,\n",
       " prompt_toolkit.buffer.EditReadOnlyBuffer,\n",
       " prompt_toolkit.buffer._Retry,\n",
       " prompt_toolkit.layout.layout.InvalidLayoutError,\n",
       " prompt_toolkit.renderer.HeightIsUnknownError,\n",
       " parso.parser.ParserSyntaxError,\n",
       " parso.parser.InternalParseError,\n",
       " parso.python.diff._PositionUpdatingFinished,\n",
       " jedi.inference.helpers.SimpleGetItemNotFound,\n",
       " jedi.inference.utils.UncaughtAttributeError,\n",
       " jedi.inference.base_value.HasNoContext,\n",
       " jedi.inference.arguments.ParamIssue,\n",
       " jedi.api.exceptions._JediError,\n",
       " jedi.api.exceptions.InternalError,\n",
       " jedi.api.exceptions.WrongVersion,\n",
       " jedi.api.exceptions.RefactoringError,\n",
       " jedi.api.helpers.OnErrorLeaf,\n",
       " jedi.api.environment.InvalidPythonEnvironment,\n",
       " email.errors.MessageError,\n",
       " email.errors.MessageParseError,\n",
       " email.errors.HeaderParseError,\n",
       " email.errors.BoundaryError,\n",
       " email.errors.MultipartConversionError,\n",
       " email.errors.CharsetError,\n",
       " uu.Error,\n",
       " http.client.HTTPException,\n",
       " http.client.NotConnected,\n",
       " http.client.InvalidURL,\n",
       " http.client.UnknownProtocol,\n",
       " http.client.UnknownTransferEncoding,\n",
       " http.client.UnimplementedFileMode,\n",
       " http.client.IncompleteRead,\n",
       " http.client.ImproperConnectionState,\n",
       " http.client.CannotSendRequest,\n",
       " http.client.CannotSendHeader,\n",
       " http.client.ResponseNotReady,\n",
       " http.client.BadStatusLine,\n",
       " http.client.RemoteDisconnected,\n",
       " http.client.LineTooLong,\n",
       " IPython.core.magics.code.InteractivelyDefined,\n",
       " IPython.terminal.embed.KillEmbedded,\n",
       " psutil.Error,\n",
       " psutil.NoSuchProcess,\n",
       " psutil.ZombieProcess,\n",
       " psutil.AccessDenied,\n",
       " psutil.TimeoutExpired,\n",
       " psutil._pslinux._Ipv6UnsupportedError,\n",
       " tornado.queues.QueueEmpty,\n",
       " tornado.queues.QueueFull,\n",
       " _pydev_bundle._pydev_saved_modules.DebuggerInitializationError,\n",
       " xml.parsers.expat.ExpatError,\n",
       " xmlrpc.client.Error,\n",
       " xmlrpc.client.ProtocolError,\n",
       " xmlrpc.client.ResponseError,\n",
       " xmlrpc.client.Fault,\n",
       " pkg_resources._vendor.pyparsing.exceptions.ParseBaseException,\n",
       " pkg_resources._vendor.pyparsing.exceptions.ParseException,\n",
       " pkg_resources._vendor.pyparsing.exceptions.ParseFatalException,\n",
       " pkg_resources._vendor.pyparsing.exceptions.ParseSyntaxException,\n",
       " pkg_resources._vendor.pyparsing.exceptions.RecursiveGrammarException,\n",
       " pkg_resources.ResolutionError,\n",
       " pkg_resources.VersionConflict,\n",
       " pkg_resources.ContextualVersionConflict,\n",
       " pkg_resources.DistributionNotFound,\n",
       " pkg_resources.UnknownExtra,\n",
       " _pydevd_bundle.pydevd_runpy._Error,\n",
       " _pydevd_bundle.pydevd_resolver.UnableToResolveVariableException,\n",
       " _pydev_bundle.pydev_monkey.InvalidTypeInArgsException]"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "get_all_subclasses(Exception)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "87b11aeb-139c-4e6c-a01f-4d595efd1bd9",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'\\n\\nFloatingPointError\\nOverflowError\\nZeroDivisionError\\n\\n'"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Q3\n",
    "\n",
    "'''\n",
    "\n",
    "FloatingPointError\n",
    "OverflowError\n",
    "ZeroDivisionError\n",
    "\n",
    "'''"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "2568b644-246e-4071-9603-b8c8f0f5f5d6",
   "metadata": {},
   "outputs": [
    {
     "ename": "ZeroDivisionError",
     "evalue": "division by zero",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[20], line 2\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;66;03m# ZerodivisionError\u001b[39;00m\n\u001b[0;32m----> 2\u001b[0m \u001b[38;5;241;43m1\u001b[39;49m\u001b[38;5;241;43m/\u001b[39;49m\u001b[38;5;241;43m0\u001b[39;49m\n",
      "\u001b[0;31mZeroDivisionError\u001b[0m: division by zero"
     ]
    }
   ],
   "source": [
    "# ZerodivisionError\n",
    "1/0"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "id": "f1d1757d-c68f-486e-87f2-5c32e997af8a",
   "metadata": {},
   "outputs": [
    {
     "ename": "OverflowError",
     "evalue": "(34, 'Numerical result out of range')",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mOverflowError\u001b[0m                             Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[42], line 5\u001b[0m\n\u001b[1;32m      2\u001b[0m n \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m9999.9999\u001b[39m\n\u001b[1;32m      4\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m i \u001b[38;5;129;01min\u001b[39;00m \u001b[38;5;28mrange\u001b[39m(\u001b[38;5;241m2\u001b[39m,\u001b[38;5;241m1000\u001b[39m):\n\u001b[0;32m----> 5\u001b[0m     n\u001b[38;5;241m=\u001b[39m \u001b[43mn\u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mi\u001b[49m\n",
      "\u001b[0;31mOverflowError\u001b[0m: (34, 'Numerical result out of range')"
     ]
    }
   ],
   "source": [
    "# OverflowError\n",
    "n = 9999.9999\n",
    "\n",
    "for i in range(2,1000):\n",
    "    n= n**i"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "34713314-7413-4820-94e0-e53016150c19",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'\\nThe LookupError class is used to handle exceptions that occur \\nwhen a key or index is used on a mapping or sequence that is not valid.\\n'"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Q4\n",
    "\n",
    "'''\n",
    "The LookupError class is used to handle exceptions that occur \n",
    "when a key or index is used on a mapping or sequence that is not valid.\n",
    "'''"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "9a34850d-f0bf-4873-9773-4d1886a7b5a9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "KeyError is 'Address' \n"
     ]
    }
   ],
   "source": [
    "dic={\"name\":\"Reslan\", \"Age\":\"27\", \"email_id\":\"reslan@gmail.com\"}\n",
    "try:\n",
    "    \n",
    "    val = dic[\"Address\"]\n",
    "except KeyError as e:\n",
    "    print(f\"KeyError is {e} \")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "57153895-feac-41e5-a705-595e8c0c0065",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "This is an Index Error and its out of range list index out of range \n"
     ]
    }
   ],
   "source": [
    "lst = [1,2,3,4]\n",
    "try:\n",
    "    val = lst[5]\n",
    "    \n",
    "except IndexError as e:\n",
    "    print(f\"This is an Index Error and its out of range {e} \")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "072d3138-b4d3-4b3c-9562-858c0cdf51bb",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'\\n\\nImport Error is an error that occur when we are trying to import a not existed Module\\nor when the module is not installed.\\n\\nRegarding ModuleNotFoundError it is a subclass for ImportError, so basically\\nwhen im trying to import a Module that not exicted , this error will show up \\n\\n'"
      ]
     },
     "execution_count": 18,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Q5\n",
    "'''\n",
    "\n",
    "Import Error is an error that occur when we are trying to import a not existed Module\n",
    "or when the module is not installed.\n",
    "\n",
    "Regarding ModuleNotFoundError it is a subclass for ImportError, so basically\n",
    "when im trying to import a Module that not exicted , this error will show up \n",
    "\n",
    "'''"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dac9e485-d6ec-4cc6-9ccc-678c1c6f2602",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Q6 \n",
    "'''\n",
    "1. Be specific in Except Clauses\n",
    "2. Use else Block sparingly\n",
    "3. Use finally for Cleanup\n",
    "4. Avoid Using Exception for Controlflow\n",
    "5. Log Exceptions\n",
    "6. Coustom Exception\n",
    "7. Handle Resource Cleanup with with statment\n",
    "8. Avoid silent Features\n",
    "9. \n",
    "'''"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
